# Form implementation generated from reading ui file 'app\ui\data_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1413, 654)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 95);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Connect.setGeometry(QtCore.QRect(60, 30, 161, 51))
        self.Connect.setStyleSheet("background-color: rgb(52, 144, 3);\n"
"font: 12pt \"Segoe UI\";\n"
"color: rgb(170, 0, 0);")
        self.Connect.setObjectName("Connect")
        self.sellect_all = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sellect_all.setGeometry(QtCore.QRect(560, 30, 171, 51))
        self.sellect_all.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"font: 12pt \"Segoe UI\";\n"
"color: rgb(0, 0, 127);")
        self.sellect_all.setObjectName("sellect_all")
        self.Load_exel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Load_exel.setGeometry(QtCore.QRect(300, 30, 171, 51))
        self.Load_exel.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.Load_exel.setObjectName("Load_exel")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 200, 341, 31))
        self.label.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 240, 221, 20))
        self.label_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 470, 221, 20))
        self.label_3.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.new_qwestion = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.new_qwestion.setGeometry(QtCore.QRect(170, 260, 221, 22))
        self.new_qwestion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.new_qwestion.setObjectName("new_qwestion")
        self.new_answer = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.new_answer.setGeometry(QtCore.QRect(170, 320, 221, 22))
        self.new_answer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.new_answer.setObjectName("new_answer")
        self.Load_new = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Load_new.setGeometry(QtCore.QRect(60, 240, 91, 61))
        self.Load_new.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 85, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.Load_new.setObjectName("Load_new")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 190, 371, 41))
        self.label_4.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 240, 181, 16))
        self.label_5.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(440, 300, 181, 16))
        self.label_6.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(170, 0, 127);")
        self.label_6.setObjectName("label_6")
        self.foungQ = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.foungQ.setGeometry(QtCore.QRect(440, 260, 181, 22))
        self.foungQ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foungQ.setObjectName("foungQ")
        self.Update_question = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Update_question.setGeometry(QtCore.QRect(440, 320, 181, 22))
        self.Update_question.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Update_question.setObjectName("Update_question")
        self.UpdatEQ = QtWidgets.QPushButton(parent=self.centralwidget)
        self.UpdatEQ.setGeometry(QtCore.QRect(570, 370, 101, 61))
        self.UpdatEQ.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(0, 0, 127);")
        self.UpdatEQ.setObjectName("UpdatEQ")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 370, 361, 31))
        self.label_7.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(170, 0, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.Del_qwestion = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Del_qwestion.setGeometry(QtCore.QRect(170, 440, 221, 22))
        self.Del_qwestion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Del_qwestion.setObjectName("Del_qwestion")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 430, 111, 81))
        self.pushButton.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(0, 0, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(630, 240, 181, 16))
        self.label_9.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(630, 300, 181, 16))
        self.label_10.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(170, 0, 127);")
        self.label_10.setObjectName("label_10")
        self.foundAns = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.foundAns.setGeometry(QtCore.QRect(630, 260, 181, 22))
        self.foundAns.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.foundAns.setObjectName("foundAns")
        self.Update_answer_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Update_answer_2.setGeometry(QtCore.QRect(630, 320, 181, 22))
        self.Update_answer_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Update_answer_2.setObjectName("Update_answer_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(880, 30, 481, 531))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.del_answer = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.del_answer.setGeometry(QtCore.QRect(170, 490, 221, 22))
        self.del_answer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.del_answer.setObjectName("del_answer")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(170, 420, 221, 20))
        self.label_11.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(170, 300, 221, 20))
        self.label_12.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1413, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Connect.setText(_translate("MainWindow", "Подключить "))
        self.sellect_all.setText(_translate("MainWindow", "Показать вопросы"))
        self.Load_exel.setText(_translate("MainWindow", "Загузить файл"))
        self.label.setText(_translate("MainWindow", "                        Загрузить строку"))
        self.label_2.setText(_translate("MainWindow", "                   Вопрос"))
        self.label_3.setText(_translate("MainWindow", "                   Ответ "))
        self.Load_new.setText(_translate("MainWindow", "Загрузить"))
        self.label_4.setText(_translate("MainWindow", "       Обновить вопрос  и  ответ"))
        self.label_5.setText(_translate("MainWindow", "                Вопрос"))
        self.label_6.setText(_translate("MainWindow", "         Новый вопрос"))
        self.UpdatEQ.setText(_translate("MainWindow", "Применить"))
        self.label_7.setText(_translate("MainWindow", "                             Удалить строку "))
        self.pushButton.setText(_translate("MainWindow", "Удалить"))
        self.label_9.setText(_translate("MainWindow", "                Ответ"))
        self.label_10.setText(_translate("MainWindow", "         Новый ответ"))
        self.label_11.setText(_translate("MainWindow", "                   Вопрос"))
        self.label_12.setText(_translate("MainWindow", "                   Ответ "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
