# Form implementation generated from reading ui file 'Main_Menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_Menu(object):
    def setupUi(self, Main_Menu):
        Main_Menu.setObjectName("Main_Menu")
        Main_Menu.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(parent=Main_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.New_Game = QtWidgets.QPushButton(parent=self.centralwidget)
        self.New_Game.setGeometry(QtCore.QRect(240, 140, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.New_Game.setFont(font)
        self.New_Game.setObjectName("New_Game")
        self.New_Tournament = QtWidgets.QPushButton(parent=self.centralwidget)
        self.New_Tournament.setGeometry(QtCore.QRect(240, 190, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.New_Tournament.setFont(font)
        self.New_Tournament.setObjectName("New_Tournament")
        self.How_to_play = QtWidgets.QPushButton(parent=self.centralwidget)
        self.How_to_play.setGeometry(QtCore.QRect(240, 240, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.How_to_play.setFont(font)
        self.How_to_play.setObjectName("How_to_play")
        self.Quit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Quit.setGeometry(QtCore.QRect(520, 440, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Quit.setFont(font)
        self.Quit.setObjectName("Quit")
        self.Prepare = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Prepare.setGeometry(QtCore.QRect(10, 400, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Prepare.setFont(font)
        self.Prepare.setObjectName("Prepare")
        self.Settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(10, 440, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Settings.setFont(font)
        self.Settings.setObjectName("Settings")
        Main_Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main_Menu)
        QtCore.QMetaObject.connectSlotsByName(Main_Menu)

    def retranslateUi(self, Main_Menu):
        _translate = QtCore.QCoreApplication.translate
        Main_Menu.setWindowTitle(_translate("Main_Menu", "Brain Ring - Moderator - Main menu"))
        self.New_Game.setText(_translate("Main_Menu", "Новая Игра"))
        self.New_Tournament.setText(_translate("Main_Menu", "Новый Турнир"))
        self.How_to_play.setText(_translate("Main_Menu", "Справка"))
        self.Quit.setText(_translate("Main_Menu", "Выход"))
        self.Prepare.setText(_translate("Main_Menu", "Подготовка игры"))
        self.Settings.setText(_translate("Main_Menu", "Настройка"))
