# Form implementation generated from reading ui file 'New_Tournament_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mod_New_Tournament(object):
    def setupUi(self, Mod_New_Tournament):
        Mod_New_Tournament.setObjectName("Mod_New_Tournament")
        Mod_New_Tournament.resize(560, 320)
        self.teamedit_1 = QtWidgets.QLineEdit(parent=Mod_New_Tournament)
        self.teamedit_1.setGeometry(QtCore.QRect(180, 60, 320, 30))
        self.teamedit_1.setObjectName("teamedit_1")
        self.teamedit_2 = QtWidgets.QLineEdit(parent=Mod_New_Tournament)
        self.teamedit_2.setGeometry(QtCore.QRect(180, 100, 320, 30))
        self.teamedit_2.setObjectName("teamedit_2")
        self.teamedit_3 = QtWidgets.QLineEdit(parent=Mod_New_Tournament)
        self.teamedit_3.setGeometry(QtCore.QRect(180, 140, 320, 30))
        self.teamedit_3.setObjectName("teamedit_3")
        self.teamedit_4 = QtWidgets.QLineEdit(parent=Mod_New_Tournament)
        self.teamedit_4.setGeometry(QtCore.QRect(180, 180, 320, 30))
        self.teamedit_4.setObjectName("teamedit_4")
        self.label_1 = QtWidgets.QLabel(parent=Mod_New_Tournament)
        self.label_1.setGeometry(QtCore.QRect(40, 60, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=Mod_New_Tournament)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Mod_New_Tournament)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Mod_New_Tournament)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cansel = QtWidgets.QPushButton(parent=Mod_New_Tournament)
        self.cansel.setGeometry(QtCore.QRect(360, 280, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cansel.setFont(font)
        self.cansel.setObjectName("cansel")
        self.draw = QtWidgets.QPushButton(parent=Mod_New_Tournament)
        self.draw.setGeometry(QtCore.QRect(460, 280, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.draw.setFont(font)
        self.draw.setObjectName("draw")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=Mod_New_Tournament)
        self.verticalScrollBar.setGeometry(QtCore.QRect(510, 60, 16, 150))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.plus = QtWidgets.QPushButton(parent=Mod_New_Tournament)
        self.plus.setGeometry(QtCore.QRect(460, 40, 15, 15))
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(parent=Mod_New_Tournament)
        self.minus.setGeometry(QtCore.QRect(480, 40, 15, 15))
        self.minus.setObjectName("minus")

        self.retranslateUi(Mod_New_Tournament)
        QtCore.QMetaObject.connectSlotsByName(Mod_New_Tournament)

    def retranslateUi(self, Mod_New_Tournament):
        _translate = QtCore.QCoreApplication.translate
        Mod_New_Tournament.setWindowTitle(_translate("Mod_New_Tournament", "Brain Ring - Moderator - New Tournament"))
        self.label_1.setText(_translate("Mod_New_Tournament", "Команда 1"))
        self.label_2.setText(_translate("Mod_New_Tournament", "Команда 2"))
        self.label_3.setText(_translate("Mod_New_Tournament", "Команда 3"))
        self.label_4.setText(_translate("Mod_New_Tournament", "Команда 4"))
        self.cansel.setText(_translate("Mod_New_Tournament", "Отмена"))
        self.draw.setText(_translate("Mod_New_Tournament", "Жеребьевка"))
        self.plus.setText(_translate("Mod_New_Tournament", "+"))
        self.minus.setText(_translate("Mod_New_Tournament", "-"))
