# Form implementation generated from reading ui file 'New_Game_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mod_New_Game(object):
    def setupUi(self, Mod_New_Game):
        Mod_New_Game.setObjectName("Mod_New_Game")
        Mod_New_Game.resize(560, 320)
        self.change_ruls = QtWidgets.QPushButton(parent=Mod_New_Game)
        self.change_ruls.setGeometry(QtCore.QRect(10, 280, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.change_ruls.setFont(font)
        self.change_ruls.setObjectName("change_ruls")
        self.cancel = QtWidgets.QPushButton(parent=Mod_New_Game)
        self.cancel.setGeometry(QtCore.QRect(360, 280, 90, 30))
        self.cancel.setObjectName("cancel")
        self.submit = QtWidgets.QPushButton(parent=Mod_New_Game)
        self.submit.setGeometry(QtCore.QRect(460, 280, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.teamdit1 = QtWidgets.QLineEdit(parent=Mod_New_Game)
        self.teamdit1.setGeometry(QtCore.QRect(170, 50, 320, 30))
        self.teamdit1.setObjectName("teamdit1")
        self.teamdit2 = QtWidgets.QLineEdit(parent=Mod_New_Game)
        self.teamdit2.setGeometry(QtCore.QRect(170, 150, 320, 30))
        self.teamdit2.setObjectName("teamdit2")
        self.label_1 = QtWidgets.QLabel(parent=Mod_New_Game)
        self.label_1.setGeometry(QtCore.QRect(30, 50, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=Mod_New_Game)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Mod_New_Game)
        QtCore.QMetaObject.connectSlotsByName(Mod_New_Game)

    def retranslateUi(self, Mod_New_Game):
        _translate = QtCore.QCoreApplication.translate
        Mod_New_Game.setWindowTitle(_translate("Mod_New_Game", "Brain Ring - Moderator - New Game"))
        self.change_ruls.setText(_translate("Mod_New_Game", "Изменить правила"))
        self.cancel.setText(_translate("Mod_New_Game", "Отмена"))
        self.submit.setText(_translate("Mod_New_Game", "Подтвердить"))
        self.label_1.setText(_translate("Mod_New_Game", "Команда 1"))
        self.label_2.setText(_translate("Mod_New_Game", "Команда 2"))
