# Form implementation generated from reading ui file 'New_Game.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mod_New_Game(object):
    def setupUi(self, Mod_New_Game):
        Mod_New_Game.setObjectName("Mod_New_Game")
        Mod_New_Game.resize(560, 320)
        self.centralwidget = QtWidgets.QWidget(parent=Mod_New_Game)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(170, 50, 320, 30))
        self.textBrowser.setObjectName("textBrowser")
        self.label_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(30, 50, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 150, 320, 30))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Change_Rules = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Change_Rules.setGeometry(QtCore.QRect(10, 280, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Change_Rules.setFont(font)
        self.Change_Rules.setObjectName("Change_Rules")
        self.Cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(380, 280, 80, 30))
        self.Cancel.setObjectName("Cancel")
        self.Submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(470, 280, 80, 30))
        self.Submit.setObjectName("Submit")
        Mod_New_Game.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mod_New_Game)
        QtCore.QMetaObject.connectSlotsByName(Mod_New_Game)

    def retranslateUi(self, Mod_New_Game):
        _translate = QtCore.QCoreApplication.translate
        Mod_New_Game.setWindowTitle(_translate("Mod_New_Game", "Brain Ring - Moderator - New Game"))
        self.label_1.setText(_translate("Mod_New_Game", "Команда  1"))
        self.label_2.setText(_translate("Mod_New_Game", "Команда  2"))
        self.Change_Rules.setText(_translate("Mod_New_Game", "Изменить правила"))
        self.Cancel.setText(_translate("Mod_New_Game", "Отмена"))
        self.Submit.setText(_translate("Mod_New_Game", "Подтвердить"))
