# Form implementation generated from reading ui file 'New_Tournament.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mod_New_Tournament(object):
    def setupUi(self, Mod_New_Tournament):
        Mod_New_Tournament.setObjectName("Mod_New_Tournament")
        Mod_New_Tournament.resize(560, 320)
        self.centralwidget = QtWidgets.QWidget(parent=Mod_New_Tournament)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_1 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_1.setGeometry(QtCore.QRect(180, 60, 320, 30))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 100, 320, 30))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(180, 140, 320, 30))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(180, 180, 320, 30))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 40, 16, 16))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 40, 16, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 100, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 140, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 180, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(510, 60, 16, 151))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.Cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Cancel.setGeometry(QtCore.QRect(380, 280, 80, 30))
        self.Cancel.setObjectName("Cancel")
        self.Draw = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Draw.setGeometry(QtCore.QRect(470, 280, 80, 30))
        self.Draw.setObjectName("Draw")
        Mod_New_Tournament.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mod_New_Tournament)
        QtCore.QMetaObject.connectSlotsByName(Mod_New_Tournament)

    def retranslateUi(self, Mod_New_Tournament):
        _translate = QtCore.QCoreApplication.translate
        Mod_New_Tournament.setWindowTitle(_translate("Mod_New_Tournament", "Brain Ring - Moderator - New Tournament"))
        self.pushButton.setText(_translate("Mod_New_Tournament", "+"))
        self.pushButton_2.setText(_translate("Mod_New_Tournament", "-"))
        self.label_3.setText(_translate("Mod_New_Tournament", "Команда 1"))
        self.label_4.setText(_translate("Mod_New_Tournament", "Команда 2"))
        self.label_5.setText(_translate("Mod_New_Tournament", "Команда 3"))
        self.label_6.setText(_translate("Mod_New_Tournament", "Команда 4"))
        self.Cancel.setText(_translate("Mod_New_Tournament", "Отмена"))
        self.Draw.setText(_translate("Mod_New_Tournament", "Жеребьевка"))
