# Form implementation generated from reading ui file 'm:\_programming\[projects]\BrainRing_current\UI\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from new_game_ui import Ui_SingleGameWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(401, 270)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(401, 270))
        MainWindow.setMaximumSize(QtCore.QSize(401, 270))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_singleGame = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_singleGame.setObjectName("btn_singleGame")
        self.gridLayout_2.addWidget(self.btn_singleGame, 0, 0, 1, 1)
        self.btn_tournament = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_tournament.setObjectName("btn_tournament")
        self.gridLayout_2.addWidget(self.btn_tournament, 1, 0, 1, 1)
        self.btn_rules = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_rules.setEnabled(True)
        self.btn_rules.setIconSize(QtCore.QSize(20, 20))
        self.btn_rules.setObjectName("btn_rules")
        self.gridLayout_2.addWidget(self.btn_rules, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_prepare = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_prepare.setObjectName("btn_prepare")
        self.gridLayout.addWidget(self.btn_prepare, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.btn_exit = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 1, 2, 1, 1)
        self.btn_settings = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_settings.setObjectName("btn_settings")
        self.gridLayout.addWidget(self.btn_settings, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 3, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_singleGame, self.btn_tournament)
        MainWindow.setTabOrder(self.btn_tournament, self.btn_rules)
        MainWindow.setTabOrder(self.btn_rules, self.btn_prepare)
        MainWindow.setTabOrder(self.btn_prepare, self.btn_settings)
        MainWindow.setTabOrder(self.btn_settings, self.btn_exit)

    def open_new_game(self):
        self.new_game = QtWidgets.QMainWindow()
        self.ui_new_game = Ui_SingleGameWindow()
        self.ui_new_game.setupUi(self.new_game)
        self.new_game.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brain Ring - Добро пожаловать!"))
        self.btn_singleGame.setText(_translate("MainWindow", "Одна игра"))
        self.btn_tournament.setText(_translate("MainWindow", "Турнир"))
        self.btn_rules.setText(_translate("MainWindow", "Правила"))
        self.btn_prepare.setText(_translate("MainWindow", "Подготовка"))
        self.btn_exit.setText(_translate("MainWindow", "Выход"))
        self.btn_settings.setText(_translate("MainWindow", "Настройки"))
