# Form implementation generated from reading ui file 'new_game_1.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_new_game(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 430)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 30, 551, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineE_team1 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineE_team1.setObjectName("lineE_team1")
        self.horizontalLayout.addWidget(self.lineE_team1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 160, 551, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineE_team2 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.lineE_team2.setObjectName("lineE_team2")
        self.horizontalLayout_2.addWidget(self.lineE_team2)
        self.btn_chRules = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_chRules.setGeometry(QtCore.QRect(410, 290, 131, 28))
        self.btn_chRules.setObjectName("btn_chRules")
        self.btn_Cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Cancel.setGeometry(QtCore.QRect(550, 290, 93, 28))
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.btn_Agree = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Agree.setGeometry(QtCore.QRect(650, 290, 93, 28))
        self.btn_Agree.setObjectName("btn_Agree")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Команда №1"))
        self.label_2.setText(_translate("MainWindow", "Команда №2"))
        self.btn_chRules.setText(_translate("MainWindow", "Изменить правила"))
        self.btn_Cancel.setText(_translate("MainWindow", "Отмена"))
        self.btn_Agree.setText(_translate("MainWindow", "Принять"))
